---
title: "Assignment 1: Introduction"
author: "Jingze Dai"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I learned how to analyze datasets using R in my statistics course during undergrad. Some of the analyzing tricks included simple regression, logistics regression, ANOVA test, multivariable regression and PCA analysis. I also self-learned a little bit about machine learning using python and joined some introductory kaggle competition before. I never tried Git before.

2. Are there any components of the course about which you feel confident?

> Answer: I know the difference among various types of regressions. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I still rely on google/ lecture notes to write codes in R, I find it quite difficult to memorize all those commands...


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/jz-dai/EDE_Fall2024/

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
